name: CI
on: [push]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: "package.json"
      - run: npm install
      - run: npm run lint

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: "package.json"
      - run: npm install
      - if: runner.os == 'Linux'
        run: xvfb-run -a npm test
      - if: runner.os != 'Linux'
        run: npm test
        env:
          TMPDIR: ${{ runner.temp }}

  release-please:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: jimeh/release-please-manifest-action@bfd8923580a274363ff9fbaf6d07484fbc8d9c6e # v2.0.0
        id: release
        with:
          target-branch-pattern: '^(main|master|release-[0-9]+(\.[0-9]+)?\.x)$'
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        marketplace:
          - vscode-marketplace
          - open-vsx
          - github-release
    needs: [lint, test]
    permissions:
      contents: write
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: "package.json"
      - run: npm install
      - if: ${{ matrix.marketplace == 'vscode-marketplace' }}
        name: Publish to VSCode Marketplace
        run: npx -y vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - if: ${{ matrix.marketplace == 'open-vsx' }}
        name: Publish to OpenVSX
        run: npx -y ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
      - if: ${{ matrix.marketplace == 'github-release' }}
        name: Publish *.vsix file to GitHub Release
        run: |
          npx -y vsce package
          gh release upload ${{ github.ref_name }} *.vsix
        env:
          GH_TOKEN: ${{ github.token }}
